apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-user-service
  name: postgres-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user-service
  template:
    metadata:
      labels:
        app: postgres-user-service
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: userdb
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: userprod
          image: postgres
          name: postgres-user-service
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-user-service-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-user-service-claim0
          persistentVolumeClaim:
            claimName: postgres-user-service-claim0

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-user-service
  name: postgres-user-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-user-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-user-service-claim0
  name: postgres-user-service-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}